name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      monetdb:
        image: monetdb/monetdb
        alias: localhost
        ports: 
          - 50000:50000

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      
      - name: Run Tests
        run: sleep 10 && julia --project=. -e "using Pkg; Pkg.test(\"MonetDB\")"
