name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      monetdb:
        image: monetdb/monetdb
        ports: 
          - 50000:50000

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      
      - name: Run Tests
        run: export HOST_ENV="monetdb" & julia --project=. -e "using Pkg; Pkg.test(\"MonetDB\")"
